export const countries = [
	{ value: '+1', label: 'United States (+1)' },
	{ value: '+44', label: 'United Kingdom (+44)' },
	{ value: '+7', label: 'Russia (+7)' },
	{ value: '+33', label: 'France (+33)' },
	{ value: '+49', label: 'Germany (+49)' },
	{ value: '+39', label: 'Italy (+39)' },
	{ value: '+34', label: 'Spain (+34)' },
	{ value: '+81', label: 'Japan (+81)' },
	{ value: '+86', label: 'China (+86)' },
	{ value: '+61', label: 'Australia (+61)' },
	{ value: '+55', label: 'Brazil (+55)' },
	{ value: '+27', label: 'South Africa (+27)' },
	{ value: '+91', label: 'India (+91)' },
	{ value: '+82', label: 'South Korea (+82)' },
	{ value: '+44', label: 'United Kingdom (+44)' },
	{ value: '+20', label: 'Egypt (+20)' },
	{ value: '+31', label: 'Netherlands (+31)' },
	{ value: '+32', label: 'Belgium (+32)' },
	{ value: '+46', label: 'Sweden (+46)' },
	{ value: '+47', label: 'Norway (+47)' },
	{ value: '+48', label: 'Poland (+48)' },
	{ value: '+53', label: 'Cuba (+53)' },
	{ value: '+52', label: 'Mexico (+52)' },
	{ value: '+61', label: 'Australia (+61)' },
	{ value: '+64', label: 'New Zealand (+64)' },
	{ value: '+90', label: 'Turkey (+90)' },
	{ value: '+91', label: 'India (+91)' },
	{ value: '+41', label: 'Switzerland (+41)' },
	{ value: '+31', label: 'Netherlands (+31)' },
	{ value: '+1', label: 'Canada (+1)' },
	{ value: '+62', label: 'Indonesia (+62)' },
	{ value: '+65', label: 'Singapore (+65)' },
	{ value: '+63', label: 'Philippines (+63)' },
	{ value: '+60', label: 'Malaysia (+60)' },
	{ value: '+55', label: 'Brazil (+55)' },
	{ value: '+98', label: 'Iran (+98)' },
	{ value: '+970', label: 'Palestine (+970)' },
	{ value: '+92', label: 'Pakistan (+92)' },
	{ value: '+98', label: 'Iran (+98)' },
	{ value: '+256', label: 'Uganda (+256)' },
	{ value: '+380', label: 'Ukraine (+380)' },
	{ value: '+254', label: 'Kenya (+254)' },
	{ value: '+233', label: 'Ghana (+233)' },
	{ value: '+251', label: 'Ethiopia (+251)' },
	{ value: '+242', label: 'Congo (+242)' },
	{ value: '+234', label: 'Nigeria (+234)' }
]
